name: Configuration de PHP
description: Configuration de PHP

inputs:
  php-version:
    description: Version de PHP à configurer
    required: true

runs:
  using: composite
  steps:
    - name: Configuration de PHP ${{ inputs.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: none
