name: Mise à jour des dépendances Composer
description: Mise à jour des dépendances Composer

runs:
  using: composite
  steps:
    - name: Mise à jour des dépendances
      shell: bash
      run: composer update --no-interaction --prefer-dist --optimize-autoloader
