name: Installation des dépendances Composer
description: Installation des dépendances Composer

runs:
  using: composite
  steps:
    - name: Installation des dépendances
      shell: bash
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
