name: Installation des dépendances NPM
description: Installation des dépendances NPM

runs:
  using: composite
  steps:
    - name: Installation des dépendances
      shell: bash
      run: npm install
