name: PHP 8.2 CI

on:
  workflow_call:

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} CI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.2'

    steps:
      - uses: pyreweb/actions/.github/actions/checkout@main

      - uses: pyreweb/actions/.github/actions/setup/php@main
        with:
          php-version: ${{ matrix.php-version }}

      - uses: pyreweb/actions/.github/actions/composer/install@main

      - uses: pyreweb/actions/.github/actions/composer/test@main
