name: pyreweb/dependencies/update

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Updating dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Refund of the deposit
        uses: actions/checkout@v4

      - name: Unique ID Generation
        id: date
        run: |
          echo "BRANCH_NAME=chore/update-dependencies-$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
          echo "PRETTY_DATE=$(date +'%d/%m/%Y à %H:%M:%S')" >> $GITHUB_ENV

      - name: PHP Configuration
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, json
          tools: composer:v2
          coverage: none

      - name: Configuring Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Restoring the Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer Caching
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Creating the .env file
        run: cp .env.example .env

      - name: Initial setup of dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress
          npm ci

      - name: Updating dependencies
        id: update
        run: |
          composer update --no-interaction --no-progress
          npm update

      - name: Frontend build
        run: npm run build

      - name: Génération de la clé d'application
        run: php artisan key:generate

      - name: Backend testing
        run: php artisan test
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'

      - name: Frontend testing
        run: npm test --if-present

      - name: Creating an automatic pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(dependencies): automatic update"
          committer: GitHub <noreply@github.com>
          author: GitHub Actions <actions@github.com>
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          title: "Automatic dependencies update - ${{ env.PRETTY_DATE }}"
          body: |
            `Pull request automatically generated by GitHub Actions.`
            
            **Run ID**: ${{ github.run_id }}
          labels: |
            github-action
            dependencies
            composer
            npm
