name: Update dependencies
description: NPM + Composer

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.5'

    steps:
      - uses: pyreweb/github_actions/.github/actions/checkout@main

      - name: Generation of the unique identifier
        id: date
        run: |
          echo "BRANCH_NAME=actions/chore-deps-update-$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - uses: pyreweb/github_actions/.github/actions/setup/php@main
        with:
          php-version: ${{ matrix.php }}

      - name: Configuring Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Restoring the Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer Caching
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Creating the .env file
        run: cp .env.example .env

      - name: Initial configuration of dependencies
        run: |
          composer install
          npm ci

      - name: Updating dependencies
        id: update
        run: |
          composer update
          npm update

      - name: Compiling the frontend
        run: npm run build

      - name: Generating the application key
        run: php artisan key:generate

      - name: Backend testing
        run: php artisan test
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'

      - name: User Interface Testing
        run: npm test --if-present

      - name: Create a pull request 
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update"
          committer: GitHub <noreply@github.com>
          author: GitHub Actions <actions@github.com>
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          title: "[Chore/Deps] Update"
          body: |
            **ID**: ${{ github.run_id }}
          labels: |
            action
            chore
            dependencies
            deps
