name: pyreweb/laravel/tests

on:
  workflow_call:

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.4', '8.5']

    steps:
      - uses: pyreweb/github_actions/.github/actions/checkout@main

      - uses: pyreweb/github_actions/.github/actions/setup/php@main
        with:
          php-version: ${{ matrix.php-version }}

      - uses: pyreweb/github_actions/.github/actions/setup/node@main

      - uses: pyreweb/github_actions/.github/actions/composer/install@main

      - uses: pyreweb/github_actions/.github/actions/npm/install@main
      
      - name: Copy .env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - uses: pyreweb/github_actions/.github/actions/npm/build@main

      - name: Run tests
        run: ./vendor/bin/pest
