name: pyreweb/laravel/linter

on:
  workflow_call:

permissions:
  contents: write

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.4', '8.5']

    steps:
      - uses: actions/checkout@v6

      - name: Configurate PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: |
          composer install
          npm install

      - name: Run composer lint
        run: composer lint

      - name: Run npm format
        run: npm run format

      - name: Run npm lint
        run: npm run lint
