name: PHP CI

on:
  workflow_call:
    inputs:
      php-version:
        description: PHP Version
        required: true
        type: string

jobs:
  tests:
    name: PHP ${{ inputs.php-version }} CI
    runs-on: ubuntu-latest

    steps:
      - uses: pyreweb/actions/.github/actions/checkout@main

      - uses: pyreweb/actions/.github/actions/setup/php@main
        with:
          php-version: ${{ inputs.php-version }}

      - uses: pyreweb/actions/.github/actions/composer/install@main

      - uses: pyreweb/actions/.github/actions/composer/test@main
